---
title: "lab1cp2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
require(readr)
require(dplyr, warn.conflicts = FALSE)
require(ggplot2)
```

```{r}
gastos_gerais = read_csv(file = "../data/gastos-cota_atividade_parlamentar.csv")
```
```{r}
#filtrar apenas PB
gastos_pb = gastos_gerais %>%
  select(sgPartido, numAno, numMes, vlrGlosa, txNomeParlamentar, vlrDocumento, txtDescricao, txtFornecedor, vlrLiquido, txtPassageiro, txtTrecho, sgUF, nuDeputadoId, numSubCota) %>%
  filter(sgUF == "PB")

#quem são os deputados da PB
parlamentares_pb = gastos_pb %>%
  select(txNomeParlamentar, sgPartido, nuDeputadoId) %>%
  distinct(txNomeParlamentar, sgPartido, nuDeputadoId)


#quais os tipos de gastos presentes nos dados

tipoDeGastos = gastos_pb%>%
  select(txtDescricao, numSubCota)%>%
  unique()
  colnames(tipoDeGastos) = c("Despesa", "ID")
  print(tipoDeGastos %>% select(ID, Despesa))
#falar do problema passagens aereas E emissao bilhete aereo encontrado na tabela acima
  
#tratar os dados para atribuir o mesmo id e descrição de despesa para as viagens aereas

gastos_pb$txtDescricao[gastos_pb$txtDescricao == "Emissão Bilhete Aéreo"] <- "PASSAGENS AÉREAS"
gastos_pb$numSubCota[gastos_pb$numSubCota == 9] <- 999

  
#os gastos seguem um padrão ou em determinados meses sofrem picos(fazer grafico de pontos interligados)
pb_2016 = gastos_pb %>%
  filter(numAno == 2016)

pb_2016_agrupado =  pb_2016%>%
  group_by(numMes, txtDescricao) %>%
  summarise(total_gasto = sum(vlrLiquido))

#existem valores negativos mas sao estornos e se anulam com o positivo correspondente
summary(pb_2016$vlrLiquido)

#em que tipo de despesas os parlamentares gastam mais recursos de sua cota(media OU para cada dep conta +1 na categoria que ele mais gastou e vê qual categoria tem maior valor empilhado)
pb_por_tipo = pb_2016 %>%
  select(txtDescricao, vlrLiquido) %>%
  group_by(txtDescricao)%>%
  summarise(total_gasto = sum(vlrLiquido))
  
ggplot(pb_por_tipo, aes(x=reorder(txtDescricao, total_gasto), y=total_gasto)) + 
  geom_bar(stat = "identity") + 
  coord_flip() +
  labs(x='Tipo da Despesa', y='Valor dos Gastos em Reais')

#que tipos de despesa tem valores que mais variam quando comparamos os deputados
pb_agrupado_parl_tipo = gastos_pb %>%
  select(txNomeParlamentar, txtDescricao, vlrLiquido) %>%
  group_by(txNomeParlamentar, txtDescricao) %>%
  summarise(total_gasto = sum(vlrLiquido))

pb_dp = pb_agrupado_parl_tipo %>%
  group_by(txtDescricao) %>%
  summarise(desvio_padrao = sd(total_gasto))

ggplot(pb_dp, aes(x=reorder(txtDescricao, desvio_padrao), y=desvio_padrao)) + 
  geom_bar(stat = "identity") +
  labs(x='Tipo da Despesa', y='Desvio Padrão')+
  coord_flip()

  
```




