---
title: "lab4cp1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# mylibs = c("readr", "dplyr", "ggplot2", "lubridate")
require(readr)
require(dplyr)
require(ggplot2)
require(lubridate)
# install.packages("resample")
require(resample)
```


```{r}
github = read_csv(file = "../data/github-users-committing-filetypes.csv")
names(github)

github = github %>% 
    mutate(
      date = lubridate::ymd(paste(the_year, the_month, month_day)), 
                  week_day = lubridate::wday(date))

py_java = github %>% 
  filter(file_extension %in% c("java", "py")) %>% 
  mutate(isWeekend = if_else(week_day %in% c("1","7"), TRUE, FALSE))

#py_java_weekday = py_java %>% 
#  filter(!(week_day %in% c("1","7"))) 

#py_java_weekend = py_java %>% 
#  filter(week_day %in% c("1","7"))
```

```{r}
#separar data frame pra py e outro pra java e rodar bootstrap pra cada um
# Agora a diferença das médias
b.diff.means = bootstrap2(py_java$users, 
                          median,
                          treatment = py_java$isWeekend)

means.diff = CI.percentile(b.diff.means, probs = c(.05, .95))
means.diff

data.frame(means.diff) %>% 
  ggplot(aes(x = "Diferença", ymin = X5., ymax = X95.)) + 
  geom_errorbar(width = .2) + 
  geom_hline(yintercept = 0, colour = "darkorange")
```


